### ISSUE TITLE
Persistencia de visualização

### ISSUE THREAD

**Issue by barickbr** [valessiobrito/viral-aedes-aegypti#13]
Adicionar alguma forma de persistir (cookie) que o usuário já viu a animação do mosquito.
Em blogs quando o usuário muda navega nos links normalmente a pagina é recarregada e seria muito chato ter o mosquito em todas as paginas de uma navegação.
Esta persistencia deveria ser opcional, com default true para persistir.

**Comment by valessiobrito** [comment]
@barickbr você consegue fazer isso? pode enviar um pull request?
acho uma ótima ideia!

**Comment by ivanssa** [comment]
@valessiobrito tem um script que uso para esse tipo de publicidade que tem umas funções de em js dontShowAgain que só mostra uma vez por usuário poderia dar um sac para adptar no banner segue o link http://meerkat.jarodtaylor.com/

**Comment by valessiobrito** [comment]
@ivanssa temos um problema em ficar carregando libs JS;  Já que estamos falando da BarraBrasil que é carregada em todos portais do Governo; Cada um com sua diferença/especificidade;    O ideal é ter algo específico para isso, sem dependências ou conflitos.   Já fiz algo similar em outros portais, é que estou sem tempo para adaptar o código para esse projeto.  
Veja aqui o código de exemplo para ser adaptado:  http://anonscm.debian.org/cgit/debconf-data/dc15.git/tree/website/script.js
Fiz para http://debconf15.debconf.org/   quando o usuário altera o contraste do site.

Se alguém tiver tempo de adaptalo e enviar um pullrequest seria ótimo.

**Comment by valessiobrito** [comment]
Feito. Acabei de colocar uma condição para verificar o cookies.

**Comment by byfdandrade** [comment]
Para quem tiver problema para manter a Pagina Atual após fechar o Banner segue função para ser adicionado ao aedes.js.

function Fechar() {
var x = location.href;
document.getElementById("Fechar").innerHTML = x;
}

E substitua na linha 67:
a href="#"  id="aegypti-close" title="Fechar"
por este:
a href="javascript:Fechar();"  id="aegypti-close" title="Fechar"
