### ISSUE TITLE
Nova raquete

### ISSUE THREAD

**Issue by angelod1as** [valessiobrito/viral-aedes-aegypti#15]
![raquete](https://cloud.githubusercontent.com/assets/13950513/12847703/3b911d48-cbfc-11e5-908c-4edf5004ba3b.png)

**Comment by valessiobrito** [comment]
@caduvieira @aurium @erikhenrique pessoal, o Angelo esta sugerindo uma raquete com Raio.. o que vocês acham?

**Comment by ivanssa** [comment]
Pessoal primeiramente, parabéns pelo projeto, axei a ação muito legal adicionei no meu portal, gostei da sugestão da raquete é mais adequada a raquete que mata o mosquito rsrs....

**Comment by valessiobrito** [comment]
Gosto do Raio/centro;  Mas não achei tão realista a estrutura da raquete.   Aqui você pode visualizar quando o mosquito estiver voando em direção contraria a interação com essa raquete: http://hackerativismo.github.io/dengame/

**Comment by angelod1as** [comment]
A raquete que mata mosquitos não se parece com a raquete de tênis. A que fiz é baseada em uma real, dessas vendidas em todo lugar. Fiz o modelo baseado em uma que tenho em casa (portanto, mais perto da realidade só se fosse uma foto).
Não entendi a segunda indagação, sobre a interação com a raquete. Ela está do mesmo tamanho e posição que a anterior.

**Comment by valessiobrito** [comment]
@angelod1as você viu ela no site que indiquei para teste? O problema esta no contraste dela, cores e contorno; Ficou muito claro;  Tentei mudar, mas como não tenho o vetor;    Também acho que o Raio ficou mais legal;  Acho que tem que fundir as duas coisas (cores e contraste de uma, com a tela de raquete eletrica);

Pode pegar o SVG (vetor) da raquete atual aqui: https://raw.githubusercontent.com/hackerativismo/viral-aedes-aegypti/master/src/raquete.svg

SVG é padrão aberto, abre com www.inkscape.org e também outros softwares para edição vetorial.

**Comment by gildasio** [comment]
+1. Massa a raquete elétrica!!

Para solucionar isso do contraste, uma borda ou uma sombra resolveria, certo? Isso mantendo as mesmas cores que já tem. Pois assim, pode colocar em sites com outros estilos.
