### ISSUE TITLE
Mudar o banner 

### ISSUE THREAD

**Issue by alynecastro** [valessiobrito/viral-aedes-aegypti#18]
Gostaria de saber se pode mudar o banner quando clica no mosquito?
No Ceará temos uma campanha e gostaria de colocar o banner da nossa companha e deixar linkando para o portal do governo federal.

**Comment by gildasio** [comment]
@alynecastro, você mesmo pode mudar, se quiser. Dando uma olhada no [script](http://hackerativismo.github.io/viral-aedes-aegypti/aedes.js), o banner está na [linha 67](https://github.com/hackerativismo/viral-aedes-aegypti/blob/master/aedes.js#L67). Vê o parâmetro `src` da tag `img`? Pois bem, só mudar ele. Basicamente, sua linha 67 ficaria:

``` html
$(document.body).append('<div id="aegypti-intervencao"><a href="http://combateaedes.saude.gov.br/" id="aegypti-banner" target="_blank" title="Faça sua parte"><img src="seu_banner.png" alt="Texto descritivo alternativo a seu banner" /></a><a href="#" id="aegypti-close" title="Fechar">Fechar</a></div>');
```

**Comment by valessiobrito** [comment]
@alynecastro deu certo?  Se sim, fecha essa Issue aqui compartilhando o Banner que você fez.

Abs,
Valessio Brito

**Comment by alynecastro** [comment]
Deu certo sim!
Brigada!
![aviso](https://cloud.githubusercontent.com/assets/14093523/13285295/9b3679ba-dad8-11e5-92cf-e85a56ece3f0.png)
