### ISSUE TITLE
Joomla Template

### ISSUE THREAD

**Issue by marciomedeirosdesouza** [valessiobrito/viral-aedes-aegypti#21]
Parabéns a todos, sensacional a idéia! Já está bombando aqui na minha cidade... pelo menos aqui o conhecimento se deu através de sites governamentais... e é justo nisso que estou opinando... sei que muitos sites estão em joomla, mas meu conhecimento não está sendo o suficiente para conseguir fazer funcionar... tentei no index do template, no index.php mas não roda. Se alguem tiver alguma sugestão pretendo instalar nos dominios que administro. Mesmo conseguindo alterar o código na unha no firebug mostra tudo carregado mas não roda... abraços...

**Comment by valessiobrito** [comment]
@marciomedeirosdesouza então, você tentou colocar a linha de código no final do site, antes do fechamento </body>

No Joomla, talvez você tenha que adicionar algum bloco de conteúdo HTML e inserir o código da página: http://hackerativismo.github.io/viral-aedes-aegypti/

**Comment by valessiobrito** [comment]
Fechando.  Duplicado no #22
