### ISSUE TITLE
joomla

### ISSUE THREAD

**Issue by marciomedeirosdesouza** [valessiobrito/viral-aedes-aegypti#22]
Bom dia...Obrigado por seu retorno! acabei de fazer no final do codigo do template como você sugeriu, mas não rodou a animação... pelo firebug o codigo parece ter carregado certinho, mas simplesmente não acontece... se quizer dar uma inspecionada... www.carangola.mg.gov.br

**Comment by valessiobrito** [comment]
@marciomedeirosdesouza seu código ficou faltando fechar corretamente o </script>.. esta sem ">"
Corriga ai, testa para ver se foi só isso mesmo.

**Comment by valessiobrito** [comment]
Acabei de acessar o site e agora o código esta fora da página, por isso não funciona.
Favor colocar o código no final da página, antes do fechamento `</body>`
Antes o problema é que você havia colado somente uma parte do código, faltando o fechamento `</script>`

O código original é esse:
`<script type='text/javascript' src='http://hackerativismo.github.io/viral-aedes-aegypti/aedes.js'></script>`

Se quer customizar, ai precisa baixar o código e colocar no seu servidor;  Com um Banner customizado.

**Comment by valessiobrito** [comment]
Feito.

**Comment by bneto300** [comment]
Eu uso Wordpress, estou tentando colocar o script no código, e do bloco html mas não executa... tentei no index.php do meu tema, mas não aparece o <body, tentei por no header.php mas não funciona, pode me dar um apoio?

**Comment by valessiobrito** [comment]
@bneto300 no wordpress, você pode editar o tema;  E abrir o template "Rodapé"  e colocar o código antes do fechamento `</body>`

**Comment by bneto300** [comment]
olá novamente, obrigado pelo retorno... tentei colocar no footer (no meu caso o template é em inglês) o código <script type='text/javascript' 
src='http://hackerativismo.github.io/viral-aedes-aegypti/aedes.js'>
</script> antes do `</body>` mas não deu certo, não fica aparecendo nada... será que estou fazendo errado? :(

**Comment by valessiobrito** [comment]
@bneto300 estranho, essa versão tem Cookies, caso os mosquitos tenham aparecido no primeiro momento; E ao matar/fechar, eles não aparecem mais.   Testa com o navegador em "modo anônimo".   Por fim, é importante que o site tenha carregado uma lib Jquery 1.7 ou superior, confira se esta carregando ou não.

**Comment by bneto300** [comment]
Olá, tentei novamente @valessiobrito , no modo anônimo ele executou uma vez, quando abro a página, mas depois, sumiu... não consegui ver onde ele mostra executando o lib Jquery 1.7, e a animação está estranha, tipo lagando... pode olhar www.barauna.rn.gov.br

**Comment by bneto300** [comment]
Outra coisa... coloquei o códgo de novo e tentei abrir com o chrome e executa... contudo não está executando bem... tipo travando
