### ISSUE TITLE
Dependência do jquery fora do ar

### ISSUE THREAD

**Issue by marciomazza** [valessiobrito/viral-aedes-aegypti#24]
Essa dependência, do arquivo `aedes.js`, está fora nesse momento (Qua Abr  6 10:35:35 BRT 2016) :
https://code.jquery.com/jquery-1.7.2.min.js

**Comment by valessiobrito** [comment]
@marciomazza ela é somente carregada se no portal não encontrar uma versão do jquery compatível;    Mas de fato, a hospedagem desse js precisa fazer parte do mesmo repositório do aedes.js;
Acabei de fixar:  https://github.com/hackerativismo/viral-aedes-aegypti/commit/b6a1802eaaaf9f5a5b34aab473b00c9533c50efe
