### ISSUE TITLE
Testar no Internet Explorer 7

### ISSUE THREAD

**Issue by valessiobrito** [valessiobrito/viral-aedes-aegypti#4]
Precisamos validar que funcione na versão IE7 ou superior.

**Comment by caduvieira** [comment]
Não creio que precise funcionar no IE7. A Microsoft não dá mais suporte nem ao IE10 desde 12 de janeiro de 2016. https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

A Barra Brasil vai deixar de dar suporte ao IE8 e vai ser em best effort basis para 9 e 10.

**Comment by valessiobrito** [comment]
Vlw!
