### ISSUE TITLE
Disponibilizar forma de desabilitar o mosquito

### ISSUE THREAD

**Issue by caduvieira** [valessiobrito/viral-aedes-aegypti#7]
Para não ser intrusivo ter forma de desabilitar o mosquito pelo usuário.

**Comment by aurium** [comment]
Agora, ao clicar no mosquito ele some. Valéssio está pensando em uma metáfora que fará todos sumirem sem esforço.

**Comment by valessiobrito** [comment]
@caduvieira na ultima atualização do código, quando você fecha o pop-up ele desabilita os mosquitos.  Considero que seja suficiente para fechar essa issue.  Agora temos a proposta de persistir pro cookies que eles devem se manter desativado para o mesmo usuário/navegador.  Essa é a issue #13
